### ISSUE TITLE
trino432+ 出现找不到 com.aliyun.jindodata.oss.JindoOssFileSystem 的问题

### ISSUE THREAD

**Issue by 670845050** [aliyun/alibabacloud-jindodata#122]
当我在trino 使用 jindodata  6.3.4 / 6.4.0 时， trino 412/431 均都可以正常读取数据（使用hive数据源，oss作为存储），当使用 trino 432+ 时，出现找不到 com.aliyun.jindodata.oss.JindoOssFileSystem 的问题，详细错误如下所示：

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class com.aliyun.jindodata.oss.JindoOssFileSystem not found
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2086)
        at com.google.common.cache.LocalCache.get(LocalCache.java:4012)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4035)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5013)
        at io.trino.cache.EvictableCache.get(EvictableCache.java:145)
        at com.google.common.cache.AbstractLoadingCache.getUnchecked(AbstractLoadingCache.java:53)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.get(CachingHiveMetastore.java:430)
        at io.trino.plugin.hive.metastore.cache.CachingHiveMetastore.getAllDatabases(CachingHiveMetastore.java:586)
        at io.trino.plugin.hive.HiveMetastoreClosure.getAllDatabases(HiveMetastoreClosure.java:73)
        at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.getAllDatabases(SemiTransactionalHiveMetastore.java:219)
        at io.trino.plugin.hive.HiveMetadata.listSchemaNames(HiveMetadata.java:477)
        at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listSchemaNames(ClassLoaderSafeConnectorMetadata.java:197)
        at io.trino.tracing.TracingConnectorMetadata.listSchemaNames(TracingConnectorMetadata.java:131)
        at io.trino.metadata.MetadataManager.listSchemaNames(MetadataManager.java:254)
        at io.trino.tracing.TracingMetadata.listSchemaNames(TracingMetadata.java:168)
        at io.trino.metadata.MetadataListing.doListSchemas(MetadataListing.java:103)
        at io.trino.metadata.MetadataListing.listSchemas(MetadataListing.java:94)
        ... 35 more

各个trino版本测试情况如下所示：
![oss测试结果](https://github.com/aliyun/alibabacloud-jindodata/assets/23412425/3ab192fe-3464-4837-9a18-25359f3306aa)

**Comment by adrian-wang** [comment]
@670845050 JindoSDK 的包是放在什么目录下的？

**Comment by 670845050** [comment]
放在 trino 的 plugin/hive/ 目录下。

**Comment by adrian-wang** [comment]
@670845050 对于高版本的trino，是否可以在plugin/hive下面创建一个hdfs子目录，然后把jindosdk放在子目录里面

**Comment by 670845050** [comment]
在 trino 443中， 将 jindosdk 的包放在 plugin/hive/hdfs 目录下，可以解决了，感谢支持。
