### ISSUE TITLE
macOS dylib支持

### ISSUE THREAD

**Issue by SIGXXL** [aliyun/alibabacloud-jindodata#81]
`Jindo Native loading failed: java.lang.RuntimeException: resource /com/aliyun/jindodata/fsx/native/libjindofsx-c61d30c8b18dcf34_20220228_135706.dylib not found, maybe incomplete compile package!
	at com.aliyun.jindodata.jni.NativeCodeLoader.extractLibraryFile(NativeCodeLoader.java:313)
	at com.aliyun.jindodata.jni.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:118)
	at com.aliyun.jindodata.jni.NativeCodeLoader.loadLibrary(NativeCodeLoader.java:91)
	at com.aliyun.jindodata.jni.NativeCodeLoader.load(NativeCodeLoader.java:53)
	at com.aliyun.jindodata.fsx.jni.FsxNative.<clinit>(FsxNative.java:20)
	at com.aliyun.jindodata.fsx.jni.JniFsxFileSystem.<init>(JniFsxFileSystem.java:11)
	at com.aliyun.jindodata.fsx.FsxFileletSystem.<init>(FsxFileletSystem.java:35)
	at com.aliyun.jindodata.fsx.FsxStore$Context.<init>(FsxStore.java:77)
	at com.aliyun.jindodata.fsx.FsxStore.initNativeStoreContext(FsxStore.java:86)
	at com.aliyun.jindodata.fsx.FsxStore.initialize(FsxStore.java:100)
	at com.aliyun.jindodata.fsx.JindoOssFileSystem.createPluginStore(JindoOssFileSystem.java:92)
	at com.aliyun.jindodata.fsx.JindoOssFileSystem.initialize(JindoOssFileSystem.java:84)`

macOS上使用，会报这个错误，解压了jindofsx-core-4.2.0.jar和jindofs-core-4.2.0.jar之后，发现macOS会自动找.dylib后缀的动态库。
https://jogamp.org/bugzilla/show_bug.cgi?id=1316
可否在打包的时候增加dylib for macOS，而不只是so？

**Comment by SIGXXL** [comment]
> 

macOS 12.0.1
Apple M1

**Comment by SIGXXL** [comment]
sorry, 4.3.0我看已经有了dylib
