### ISSUE TITLE
debain-slime镜像中使用jindofs-sdk-3.7.3.jar遇到JIN问题

### ISSUE THREAD

**Issue by blackcheckren** [aliyun/alibabacloud-jindodata#99]
由于项目要求，需要使用Spark读取OSS上的文件，看到jindofs-sdk能够支持这一功能而且性能更好，遂决定在项目中引入，但是在测试的过程中发现在k8s环境中无法完成文件的读取，遇到`java.lang.UnsatisfiedLinkError: 'void com.alibaba.jboot.JbootNative.initNative()'` 问题，经过查找发现可能是环境中缺少某些动态链接库导致的。下面是项目组件版本和镜像信息：
Hadoop 3.2.0
Spark 3.1.3
OpenJDK 11.0.16
基础镜像为：debain-slime

报错的信息如下：
`23/04/26 10:04:25 INFO SparkContext: Successfully stopped SparkContext
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void com.alibaba.jboot.JbootNative.initNative()'
	at com.alibaba.jboot.JbootNative.initNative(Native Method)
	at com.alibaba.jboot.JbootNative.init(JbootNative.java:56)
	at com.alibaba.jboot.JbootNative.initialize(JbootNative.java:40)
	at com.alibaba.jboot.JbootNative.instance(JbootNative.java:31)
	at com.alibaba.jboot.JbootNative.initOnceNativeClass(JbootNative.java:74)
	at com.alibaba.jboot.JbootCache.<init>(JbootCache.java:11)
	at com.aliyun.emr.fs.internal.ossnative.OssFileletSystem.<init>(OssFileletSystem.java:37)
	at com.aliyun.emr.fs.internal.ossnative.OssNativeStore$Context.<init>(OssNativeStore.java:99)
	at com.aliyun.emr.fs.oss.JindoOssFileSystem.initNativeStoreContext(JindoOssFileSystem.java:138)
	at com.aliyun.emr.fs.oss.JindoOssFileSystem.initialize(JindoOssFileSystem.java:133)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3303)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:361)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:46)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:377)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:325)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:307)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:307)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:239)
	at js.sgcc.com.cn.demo.OssJindosFDSupportDemo$.main(OssJindosFDSupportDemo.scala:21)
	at js.sgcc.com.cn.demo.OssJindosFDSupportDemo.main(OssJindosFDSupportDemo.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
23/04/26 10:04:25 INFO ShutdownHookManager: Shutdown hook called
23/04/26 10:04:25 INFO ShutdownHookManager: Deleting directory /tmp/spark-97956ae8-0cc5-4bdc-aca5-caaaabfd55b0
23/04/26 10:04:25 INFO ShutdownHookManager: Deleting directory /var/data/spark-ddc7adc3-2b2e-408c-bd02-c6127585d64f/spark-110ae79a-bf72-48d3-8937-e2da450b9cc0`

**Comment by yanbinyang** [comment]
> 

debain-slime我们应该是兼容的。不过，3.x我们已经逐渐不再维护了哈。
建议下载最新的4.x版本再试一下，下载链接：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/jindodata_download.md

**Comment by blackcheckren** [comment]
> > 
> 
> debain-slime我们应该是兼容的。不过，3.x我们已经逐渐不再维护了哈。 建议下载最新的4.x版本再试一下，下载链接：https://github.com/aliyun/alibabacloud-jindodata/blob/master/docs/user/4.x/jindodata_download.md

感谢回复，看到了4版本中对debain系统需要安装相关组件的描述，调整一下镜像，待会再进行测试
